# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

import pytest
import selenium
import time
from selenium import webdriver
import selenium.webdriver as webdriver
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.remote.webelement import WebElement
from selenium.webdriver.support.wait import WebDriverWait


@pytest.fixture(autouse=True)
def driver():
    chrome_driver_binary = r'.\drivers\chromedriver'
    driver = webdriver.Chrome(chrome_driver_binary)
    yield driver
    driver.close()

def test_delete_product(driver):
    
  driver.get("https://www.telerik.com/")
  driver.set_window_size(1550, 926)
  driver.find_element(By.CSS_SELECTOR, ".TK-Menu-Item:nth-child(5) > .TK-Menu-Item-Link").click()
  driver.find_element(By.CSS_SELECTOR, ".UI > div > .Btn").click()
  driver.find_element(By.LINK_TEXT, "Delete Item").click()
  
